package com.example.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.data.NoteEntry
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {

    fun generateNotePdf(context: Context, note: NoteEntry): File {
        val pdfDocument = PdfDocument()
        val pageWidth = 595 // Standard A4 width in points (72 dpi)
        val pageHeight = 842 // Standard A4 height in points

        // Paints
        val titlePaint = Paint().apply {
            color = Color.parseColor("#7C4DFF") // Electric Violet
            textSize = 24f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val headerPaint = Paint().apply {
            color = Color.parseColor("#00E5FF") // Cyan
            textSize = 18f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val bodyPaint = Paint().apply {
            color = Color.parseColor("#1A1A2E") // Dark Text on White Paper
            textSize = 12f
            typeface = Typeface.DEFAULT
            isAntiAlias = true
        }

        val boldBodyPaint = Paint().apply {
            color = Color.parseColor("#0A0A0A")
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val quotePaint = Paint().apply {
            color = Color.parseColor("#4A4A6A")
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
            isAntiAlias = true
        }

        val boxBgPaint = Paint().apply {
            color = Color.parseColor("#F0ECFF")
            style = Paint.Style.FILL
            isAntiAlias = true
        }

        val boxBorderPaint = Paint().apply {
            color = Color.parseColor("#7C4DFF")
            style = Paint.Style.STROKE
            strokeWidth = 2f
            isAntiAlias = true
        }

        val dotPaint = Paint().apply {
            color = Color.parseColor("#00E5FF")
            style = Paint.Style.FILL
            isAntiAlias = true
        }

        // PAGE 1: COVER PAGE
        val coverPageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val coverPage = pdfDocument.startPage(coverPageInfo)
        val canvas = coverPage.canvas

        // Dark banner at top of cover page
        val bannerPaint = Paint().apply { color = Color.parseColor("#0A0A0A") }
        canvas.drawRect(0f, 0f, pageWidth.toFloat(), 180f, bannerPaint)

        // App Header
        titlePaint.color = Color.parseColor("#FFFFFF")
        canvas.drawText("MY COLLEGE NOTES", 40f, 60f, titlePaint)

        // Subtitle badge
        val badgePaint = Paint().apply { color = Color.parseColor("#7C4DFF") }
        val badgeRect = RectF(40f, 85f, 240f, 115f)
        canvas.drawRoundRect(badgeRect, 10f, 10f, badgePaint)

        val badgeTextPaint = Paint().apply {
            color = Color.WHITE
            textSize = 10f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        canvas.drawText("⚡ GENERATED BY GEMINI AI", 52f, 104f, badgeTextPaint)

        // Metadata section
        var currentY = 220f
        val labelPaint = Paint().apply {
            color = Color.parseColor("#7C4DFF")
            textSize = 14f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val valuePaint = Paint().apply {
            color = Color.parseColor("#1A1A2E")
            textSize = 14f
            typeface = Typeface.DEFAULT
        }

        canvas.drawText("Subject:", 40f, currentY, labelPaint)
        canvas.drawText(note.subject, 140f, currentY, valuePaint)
        currentY += 35f

        canvas.drawText("Title:", 40f, currentY, labelPaint)
        canvas.drawText(note.title, 140f, currentY, valuePaint)
        currentY += 35f

        canvas.drawText("Date & Day:", 40f, currentY, labelPaint)
        canvas.drawText("${note.date} (${note.dayOfWeek})", 140f, currentY, valuePaint)
        currentY += 35f

        canvas.drawText("Class Time:", 40f, currentY, labelPaint)
        canvas.drawText(note.classTime, 140f, currentY, valuePaint)
        currentY += 35f

        canvas.drawText("Teacher:", 40f, currentY, labelPaint)
        canvas.drawText(note.teacher, 140f, currentY, valuePaint)
        currentY += 35f

        canvas.drawText("Confidence:", 40f, currentY, labelPaint)
        canvas.drawText("${note.confidenceScore}% (Gemini Audio Verification)", 140f, currentY, valuePaint)
        currentY += 50f

        // Cover Box: Topics Summary
        val topicBoxRect = RectF(40f, currentY, pageWidth - 40f, currentY + 220f)
        canvas.drawRoundRect(topicBoxRect, 12f, 12f, boxBgPaint)
        canvas.drawRoundRect(topicBoxRect, 12f, 12f, boxBorderPaint)

        canvas.drawText("ACADEMIC TOPICS COVERED", 60f, currentY + 35f, labelPaint)
        var topicY = currentY + 70f
        note.topics.forEach { topic ->
            canvas.drawCircle(70f, topicY - 4f, 4f, dotPaint)
            canvas.drawText(topic, 85f, topicY, bodyPaint)
            topicY += 28f
        }

        // Footer
        val footerPaint = Paint().apply {
            color = Color.parseColor("#888888")
            textSize = 10f
        }
        canvas.drawText("Page 1 of 2 • MY COLLEGE NOTES Android Companion", 40f, pageHeight - 40f, footerPaint)

        pdfDocument.finishPage(coverPage)

        // PAGE 2: CONTENT PAGE
        val contentPageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 2).create()
        val contentPage = pdfDocument.startPage(contentPageInfo)
        val canvas2 = contentPage.canvas

        // Reset Y
        var y2 = 50f
        titlePaint.color = Color.parseColor("#7C4DFF")
        titlePaint.textSize = 18f
        canvas2.drawText("STRUCTURED LECTURE NOTES", 40f, y2, titlePaint)
        y2 += 30f

        val lines = note.summaryMarkdown.lines()
        lines.forEach { line ->
            if (y2 > pageHeight - 80f) return@forEach // simple single page content clamp for now

            when {
                line.startsWith("#") -> {
                    y2 += 10f
                    val headerText = line.replace("#", "").trim()
                    canvas2.drawText(headerText, 40f, y2, headerPaint)
                    y2 += 22f
                }
                line.startsWith("-") || line.startsWith("*") -> {
                    val bulletText = line.substring(1).trim()
                    canvas2.drawCircle(48f, y2 - 4f, 3.5f, dotPaint)
                    canvas2.drawText(bulletText.take(70), 60f, y2, bodyPaint)
                    y2 += 18f
                }
                line.startsWith(">") -> {
                    val quoteText = line.substring(1).trim()
                    val quoteRect = RectF(40f, y2 - 12f, pageWidth - 40f, y2 + 18f)
                    canvas2.drawRoundRect(quoteRect, 6f, 6f, boxBgPaint)
                    canvas2.drawText("Teacher Note: $quoteText", 50f, y2 + 2f, quotePaint)
                    y2 += 28f
                }
                else -> {
                    if (line.trim().isNotEmpty()) {
                        canvas2.drawText(line.trim().take(75), 40f, y2, bodyPaint)
                        y2 += 18f
                    }
                }
            }
        }

        // Final page section: Audio recording QR/Link representation
        y2 += 20f
        val audioBoxRect = RectF(40f, pageHeight - 120f, pageWidth - 40f, pageHeight - 50f)
        val audioBgPaint = Paint().apply { color = Color.parseColor("#E0F7FA") }
        val audioBorderPaint = Paint().apply { color = Color.parseColor("#00E5FF"); style = Paint.Style.STROKE; strokeWidth = 1.5f }
        canvas2.drawRoundRect(audioBoxRect, 8f, 8f, audioBgPaint)
        canvas2.drawRoundRect(audioBoxRect, 8f, 8f, audioBorderPaint)

        canvas2.drawText("🎙️ LINKED LECTURE RECORDING FILE", 60f, pageHeight - 95f, boldBodyPaint)
        val pathText = if (note.audioFilePath.isNotEmpty()) note.audioFilePath else "Saved locally in /MyCollegeNotes/Recordings/"
        canvas2.drawText("File Path: $pathText", 60f, pageHeight - 75f, bodyPaint)
        canvas2.drawText("Page 2 of 2 • MY COLLEGE NOTES", 40f, pageHeight - 20f, footerPaint)

        pdfDocument.finishPage(contentPage)

        // Save PDF to storage
        val pdfDir = File(context.filesDir, "MyCollegeNotes/PDFs/${note.subject.replace(" ", "_")}")
        if (!pdfDir.exists()) pdfDir.mkdirs()

        val pdfFile = File(pdfDir, "Note_${note.id}_${System.currentTimeMillis()}.pdf")
        try {
            val outputStream = FileOutputStream(pdfFile)
            pdfDocument.writeTo(outputStream)
            outputStream.close()
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            pdfDocument.close()
        }

        return pdfFile
    }
}
